### ISSUE TITLE
Would you be interested in creating a hotkey for adding a folder to the bookmarks?

### ISSUE THREAD

**Issue by sterbalr** [theborg3of5/BookmarkFolderHotkeys#1]
Would you be interested in creating a hotkey for adding a folder to the bookmarks?

**Comment by theborg3of5** [comment]
To be honest, I'm not actively using or developing this anymore. If you're interested in that functionality, you're welcome to add it yourself - please submit a pull request if you do!

**Comment by sterbalr** [comment]
It is outside of my personal expertise. Thanks for the quick response!
